[[IgnoredVulns]]
id = "CVE-2026-45819"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "CVE-2026-73088"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "CVE-2026-73089"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "CVE-2026-40345"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "CVE-2026-75604"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "GHSA-2xp9-vwfh-vxw4"
ignoreUntil = "2028-12-31"

[[IgnoredVulns]]
id = "GHSA-rgj7-g3m4-5g8c"
ignoreUntil = "2028-12-31"
