name: OSV-Scanner

on:
  pull_request:
    branches: [main, developmental]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@9a498708959aeaef5ef730655706c5a1df1edbc2
        with:
          scan-args: |-
            --recursive
            .
